### ISSUE TITLE
Under debug mode '-d' file AuditLogCollector.log shows 0 content blob

### ISSUE THREAD

**Issue by asadzz** [ddbnl/office365-audit-log-collector#10]
Hello,
First I like to thank you guys for making such useful script/tool.

I have most things setup, with small change that instead of tcp stream to be gray log its logstash which is configured to received json data on given port defined under 

> ./AuditLogCollector.py

The output of **AuditLogCollector.log**

> DEBUG:root:Getting available content for type: "Audit.Exchange"
> DEBUG:root:Getting available content for type: "Audit.AzureActiveDirectory"
> DEBUG:root:Making API request using URL: "https://manage.office.com/api/v1.0/71a9fb03-b345-4df8-a29a-461c5b94797e/activity/feed/subscriptions/content?contentType=Audit.Exchange&startTime=2019-08-12T20:58:54&endTime=2019-08-12T21:58:54&PublisherIdentifier=0110bb34-3fc5-4d21-b8fa -827437ab7597"
> DEBUG:root:Making API request using URL: "https://manage.office.com/api/v1.0/71a9fb03-b345-4df8-a29a-461c5b94797e/activity/feed/subscriptions/content?contentType=Audit.AzureActiveDirectory&startTime=2019-08-12T20:58:54&endTime=2019-08-12T21:58:54&PublisherIdentifier=0110bb34-3fc5-4d21-b8fa -827437ab7597"
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
> DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /71a9fb03-b345-4df8-a29a-461c5b94797e/oauth2/token HTTP/1.1" 200 1427
> DEBUG:root:Logged in
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): manage.office.com:443
> DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /71a9fb03-b345-4df8-a29a-461c5b94797e/oauth2/token HTTP/1.1" 200 1427
> DEBUG:root:Logged in
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): manage.office.com:443
> DEBUG:urllib3.connectionpool:https://manage.office.com:443 "GET /api/v1.0/71a9fb03-b345-4df8-a29a-461c5b94797e/activity/feed/subscriptions/content?contentType=Audit.AzureActiveDirectory&startTime=2019-08-12T20:58:54&endTime=2019-08-12T21:58:54&PublisherIdentifier=0110bb04-3fc5-4d21-b8fa%20-827437ab7597 HTTP/1.1" 200 2
> DEBUG:root:Got 0 content blobs of type: "Audit.AzureActiveDirectory"
> DEBUG:urllib3.connectionpool:https://manage.office.com:443 "GET /api/v1.0/71a9fb03-b345-4df8-a29a-461c5b94797e/activity/feed/subscriptions/content?contentType=Audit.Exchange&startTime=2019-08-12T20:58:54&endTime=2019-08-12T21:58:54&PublisherIdentifier=0110bb34-3fc5-4d21-b8fa%20-827437ab7597 HTTP/1.1" 200 2
> DEBUG:root:Got 0 content blobs of type: "Audit.Exchange"

On 0365 i made considerable sensitive changes in order to generate audit logs. See attachments
![comp audit](https://user-images.githubusercontent.com/7777434/62883663-6d613600-bce9-11e9-9381-319633675b8f.PNG)
![log audit](https://user-images.githubusercontent.com/7777434/62883668-70f4bd00-bce9-11e9-9576-429f448aa0eb.png)

Also, the time is in UTC, but when retrieved also seen in screenshot its in local-time, should API request be made against local time ?

**Comment by ddbnl** [comment]
I was unable to work on this repo for a while, sorry for the very late reply. Do you still need help with this issue? I will leave it open for a while longer.

Start- and end date in the script should be in UTC time and american date format as far as I know (I ran into this issue before with ComplianceSearch powershell commands using KQL search language).
