### ISSUE TITLE
Errors on Debian 10

### ISSUE THREAD

**Issue by phokur** [ddbnl/office365-audit-log-collector#16]
Using the Linux executable I get:
`Error loading Python lib '/tmp/_MEIfpmUZU/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /tmp/_MEIfpmUZU/libpython3.8.so.1.0)`

Updated Debian and ldd --version = `ldd (Debian GLIBC 2.28-10) 2.28`

Tried running from the source python files but I get hung up on pip installing the requirements.txt
```
ERROR: Could not find a version that satisfies the requirement kivy-deps.angle==0.3.2 (from versions: none)
ERROR: No matching distribution found for kivy-deps.angle==0.3.2
```

**Comment by phokur** [comment]
Upgrading to Debian 11 resolved issues.

**Comment by LeonardoSanBenitez** [comment]
A small help for the ones that had the same problem:
I ran into this issue when using Azure Functions with custom containers. 
I was using as base the recommended Microsoft images for python listed on [Microsoft's Dockerhub](https://hub.docker.com/_/microsoft-azure-functions-python), where you can see which images are based on Debian 10 (where this tool doesn't work) and which are based on Debian 11 (where this tool works fine).
I can report that I successfully used this tool with the base image `mcr.microsoft.com/azure-functions/python:4-python3.9`

**Comment by ddbnl** [comment]
Thanks for the update on that issue, I'll be sure to include that in the readme on the next commit!
