### ISSUE TITLE
Lacking certificate validation

### ISSUE THREAD

**Issue by Doctor-love** [ddbnl/office365-audit-log-collector#2]
The HTTP(S) requests performed by the scripts have been configured to not validate the identity (certificate) of the Office365 services:

```
[...]
r = requests.post(auth_url, headers=headers, data=data, verify=False)
[...]
```

This makes the connections vulnerable to Man-In-The-Middle attacks, which could result in the exposure of access credentials and other sensitive information.

Since the scripts use the "requests"  module (which supports/uses ["certifi"](https://certifiio.readthedocs.io/en/latest/))  and Office365 provides verifiable certificates, it should not be an issue to enable validation.

**Comment by ddbnl** [comment]
Agreed; could you check if the [latest commit](https://github.com/ddbnl/office365-audit-log-collector/commit/d5a03d0072f51d775ec08f267e2c79babec2efa6) allows you to retrieve the audit logs securely?

**Comment by Doctor-love** [comment]
Seems like you have over complicated a lot of things - and you hard-code paths to your own home directory. If you would just remove "verify=False" or set it to "verify=True", that would be sufficient.

**Comment by ddbnl** [comment]
I incorrectly assumed you had to supply the certificate, thanks for the heads up. Updated.
