### ISSUE TITLE
Error logging in: "'access_token'"

### ISSUE THREAD

**Issue by MaKlick** [ddbnl/office365-audit-log-collector#36]
Hello

When I try to run the collector with the tenant ID, client key, secret key and the fullConfig.yaml I get the error message "Error logging in: "'access_token'". I don't know what could be the problem behind this. 

Thanks in advance.

**Comment by byredhat01** [comment]
Hello, I have same issue what can we do.
<img width="964" alt="Screenshot 2022-11-06 at 18 01 06" src="https://user-images.githubusercontent.com/44033446/200184266-7e9e41d3-5d04-4778-8ccf-d9c57be0e324.png">

**Comment by Djegger** [comment]
Hello,

 Did you find the answer ?
