### ISSUE TITLE
Getting occasional failures, via Linux cron job script [latest binary]

### ISSUE THREAD

**Issue by rynstack** [ddbnl/office365-audit-log-collector#37]
Typically shows the same output every time it errs:

> 
> Starting run @ 2022-10-05 06:50:04.387915. Content: deque(['Audit.General', 'Audit.AzureActiveDirectory', 'Audit.Exchange', 'Audit.SharePoint', 'DLP.All']).
> Traceback (most recent call last):
> File "AuditLogCollector.py", line 699, in <module>
> File "AuditLogCollector.py", line 67, in run
> File "AuditLogCollector.py", line 80, in run_once
> File "AuditLogCollector.py", line 113, in receive_results_from_rust_engine
> File "json/__init__.py", line 357, in loads
> File "json/decoder.py", line 337, in decode
> File "json/decoder.py", line 355, in raw_decode
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> [1061404] Failed to execute script 'AuditLogCollector' due to unhandled exception!
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/api_connection.rs:254:57
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Gill-Bates** [comment]
Having the same issue. Any suggestion?

**Comment by ddbnl** [comment]
Sorry for the late reply, due to my day job I was unable to work on the repo for a while.

There is an unhandled error in the engine, I will update to handle it by retrying or dropping the message if necessary, rather than crashing. I'll update here when a new version is available.
