### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by giggio** [ddbnl/office365-audit-log-collector#41]
Great tool, thanks!
Are you planning on publishing a Docker image to Docker Hub? We could send a PR.

**Comment by danpoltawski** [comment]
I'm interesetd in your dockerfile :)

**Comment by ddbnl** [comment]
A new version is available with a docker image in the github container registry. See the repo readme for details and instructions.

Note that to reduce the number of bugs and improve performance, the last version has been fully rewritten in Rust, and as a result there are some small breaking changes (command line args). Check the readme for the correct syntax.
