### ISSUE TITLE
Release Version Different

### ISSUE THREAD

**Issue by htschannerl** [ddbnl/office365-audit-log-collector#42]
Hello, 

Very great tool.

The release version here https://github.com/ddbnl/office365-audit-log-collector/releases/tag/v2.1 is different from the version in the repo.
https://github.com/ddbnl/office365-audit-log-collector/tree/master/Linux

**Comment by ddbnl** [comment]
A new version is available, the new release has the right version.

Note that to reduce the number of bugs and improve performance, the last version has been fully rewritten in Rust, and as a result there are some small breaking changes (command line args). Check the readme for the correct syntax. It is also recommended to run the tool using the container that has been made available. See the repo readme for instructions.

If instead you want to keep using the binary, a new version is available here: https://github.com/ddbnl/office365-audit-log-collector/releases/tag/v2.2
