### ISSUE TITLE
Trouble getting it started

### ISSUE THREAD

**Issue by Jules821995** [ddbnl/office365-audit-log-collector#43]
Hi There,
ist there any working config for Linux?

I have problems to install this in Linux (Ubuntu 20.04).
I have registered an app, but fail to run the script.

**Comment by brummybird** [comment]
Hi Jules, 
Where are you getting stuck? I am also having trouble with the AuditLogCollector.py 
Pip requirements were not met so I needed to install the modules.
Now getting prtg.sensor module not found
alc module not found
fluent.sender not found
I am working through the problems but if you ever fixed your problems please let me know :)

**Comment by ddbnl** [comment]
Sorry for the late reply, due to my day job I was unable to work on the repo for a while.

If you still require assistance let me know, and we can look at the issue(s) together.

**Comment by ddbnl** [comment]
Closing the issue; if you still require assistance feel free to reply.
