### ISSUE TITLE
Issues when connecting to GCC Tenant

### ISSUE THREAD

**Issue by Logan-Kranz** [ddbnl/office365-audit-log-collector#44]
I've been having issues connecting using a few different systems and I'm thinking it's related to being a GCC tenant and using a different management API URL. I will paste the two different error snippets I've received. 

Is it possible to set the URL in the config.yaml file?

```
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[5724] Failed to execute script 'AuditLogCollector' due to unhandled exception!
```

```
HTTPSConnectionPool(host='manage.office.com', port=443): Max retries exceeded with url: /api/v1.0/[TENANT_ID]/activity/feed/subscriptions/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[36496] Failed to execute script 'AuditLogCollector' due to unhandled exception!
```

**Comment by ddbnl** [comment]
I was unable to work on this repo for a long while. Would you still like me to resolve this? If so I could add support for a custom URL. Let me know if so.

**Comment by ddbnl** [comment]
Closed due to inactivity, if you still  have issues feel free to create another.
