### ISSUE TITLE
Panic: `OS can't spawn a new worker thread`

### ISSUE THREAD

**Issue by giggio** [ddbnl/office365-audit-log-collector#46]
I'm getting this error sometimes:

```
thread '<unnamed>' panicked at 'OS can't spawn a new worker thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:291:14
```

I'll run with `RUST_BACKTRACE=1` to try and get more info, I have no other signals of what could be happening.

**Comment by ddbnl** [comment]
Sorry for the late reply, due to my day job I was unable to work on the repo for a while.

I'll investigate. If you are still around, could you let me know what you are/were running on?

**Comment by giggio** [comment]
@ddbnl I have left the company I was working on, I can't add more information anymore. Feel free to close if you want.

**Comment by ddbnl** [comment]
No worries; nevertheless, the issues has been fixed in the latest version.
