### ISSUE TITLE
Schedule stops on panic but process does not stop

### ISSUE THREAD

**Issue by giggio** [ddbnl/office365-audit-log-collector#47]
This is related to #46. When a panic happens and the schedule is set it stops running the schedule, but the process keeps running, so log collections are lost.

**Comment by ddbnl** [comment]
A new version is available that should have fixed this issue. 

Note that to reduce the number of bugs and improve performance, the last version has been fully rewritten in Rust, and as a result there are some small breaking changes (command line args). Check the readme for the correct syntax. It is also recommended to run the tool using the container that has been made available. See the repo readme for instructions.

If instead you want to keep using the binary, a new version is available here: https://github.com/ddbnl/office365-audit-log-collector/releases/tag/v2.2
