### ISSUE TITLE
Error access_token missing field 

### ISSUE THREAD

**Issue by Djegger** [ddbnl/office365-audit-log-collector#53]
Hi guys ! 

I've encountered an issue when trying to run LINUX-OfficeAuditLogCollector-V2.3 using this command : ./LINUX-OfficeAuditLogCollector-V2.3 client_id="xxxxx" tenant_id="xxxx" secret_key="_xxxx" --config graylog.yaml

Here is what is returned : Starting run @ 2023-11-21 11:20:11.651446. Content: deque(['Audit.General', 'Audit.AzureActiveDirectory', 'Audit.Exchange', 'Audit.SharePoint', 'DLP.All']).
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 560) }', src/api_connection.rs:57:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "AuditLogCollector.py", line 712, in <module>
  File "AuditLogCollector.py", line 71, in run
  File "AuditLogCollector.py", line 84, in run_once
  File "AuditLogCollector.py", line 105, in receive_results_from_rust_engine
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 560) }
[109274] Failed to execute script 'AuditLogCollector' due to unhandled exception!

Do you guys maybe have an idea of what's wrong ? 
Thanks in advance.

**Comment by hofq** [comment]
try running it without the assigning of vars in the Arguments in the App, like:

OfficeAuditLogCollector(.exe) your-tenant-id your-client-id your-secret --config %path/to/config.yaml%

**Comment by ddbnl** [comment]
Sorry for the late reply, due to my day job I was unable to work on the repo for a while. 

Do you still require assistance or did the above reply solve your issue?

**Comment by ddbnl** [comment]
Closing the issue; if you still require assistance feel free to reply.
