### ISSUE TITLE
Error: Error logging in: "'access_token'"

### ISSUE THREAD

**Issue by ne0x86** [ddbnl/office365-audit-log-collector#58]
Hi. Im getting this error when lauching .exe : Error logging in: "'access_token'"

I check so many times tenant id, client id an key, and all its ok. I dont know what I should check.

Thanks

**Comment by ddbnl** [comment]
Hi,

Sorry for the late reply, I was unable to work on this repo for a while.

If the tenant, app id and app key are all correct, I assume it would have to be the API permissons. Can you confirm if the app registration has the following permissions (and if they have 'admin consent')? The full instructions are in the repo readme.

Office 365 Management APIs' > 'Application permissions':
        Check 'ActivityFeed.Read'
        Check 'ActivityFeed.ReadDlp'

**Comment by ne0x86** [comment]
Hi. First of all, thank you for your response.

I have reconfigured everything from 0 and now I no longer receive the same error:

Now I am getting this:

Traceback (most recent call last):
   File "AuditLogCollector.py", line 699, in <module>
   File "AuditLogCollector.py", line 67, in run
   File "AuditLogCollector.py", line 75, in run_once
   File "AuditLogCollector.py", line 170, in _prepare_to_run
   File "AuditLogCollector.py", line 262, in _auto_subscribe
RuntimeError: Auto subscribe enabled but could not get subscription status
[16820] Failed to execute script 'AuditLogCollector' due to unhandled exception!

ANy idea how I can fix it?

**Comment by ne0x86** [comment]
Nothing, its fixed grant permissions on api access. Sorry

**Comment by ddbnl** [comment]
Good to hear! No worries. I'll close the issue.
