### ISSUE TITLE
Feature Request - Collect since previous one

### ISSUE THREAD

**Issue by mathieuchateau** [ddbnl/office365-audit-log-collector#7]
Collect is based on 1 hour time delta. Sometimes, collect may not have start for some times, and so data will be missed.

Would be better to keep a timestamp, like in known_content file, to calculate correct start date to use.

**Comment by branchnetconsulting** [comment]
I agree.  If this tool could maintain some kind of state or bookmark indicating where it left off with collecting log content in the previous cycle, then there would be much less risk of gaps or overlaps in the collected log materials over time.

**Comment by ddbnl** [comment]
Late reply as I was away for a while. 

I have added parameters for custom start dates in amount of hours or days to go back. Also added a parameter for resuming the script for last successful run time for each content type. Now you should not miss any logs if the script didn't run for a while.

See 71efe69.

Thank you for the suggestion.
